### ISSUE TITLE
Build producing error: redefinition of ‘struct sha256_state’

### ISSUE THREAD

**Issue by itsbeakerma** [norazly/Comfast-CF-811AC#1]
Let me know if/what other information you need.

Building on a MacBookPro15,1

$ uname -a
Linux littlemac 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ ./dkms-install.sh
You must run this with superuser priviliges.  Try "sudo ./dkms-install.sh"

$ sudo ./dkms-install.sh
About to run dkms install steps...

Creating symlink /var/lib/dkms/rtl8821CU/5.4.1/source ->
                 /usr/src/rtl8821CU-5.4.1

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' KVER=5.8.0-55-generic...(bad exit status: 2)
ERROR (dkms apport): binary package for rtl8821CU: 5.4.1 not found
Error! Bad return status for module build on kernel: 5.8.0-55-generic (x86_64)
Consult /var/lib/dkms/rtl8821CU/5.4.1/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' KVER=5.8.0-55-generic...(bad exit status: 2)
ERROR (dkms apport): binary package for rtl8821CU: 5.4.1 not found
Error! Bad return status for module build on kernel: 5.8.0-55-generic (x86_64)
Consult /var/lib/dkms/rtl8821CU/5.4.1/build/make.log for more information.
Finished running dkms install steps.

$ cat /var/lib/dkms/rtl8821CU/5.4.1/build/make.log
DKMS make.log for rtl8821CU-5.4.1 for kernel 5.8.0-55-generic (x86_64)
Wed 07 Jul 2021 09:15:52 AM EDT
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.8.0-55-generic/build M=/var/lib/dkms/rtl8821CU/5.4.1/build  modules
make[1]: Entering directory '/usr/src/linux-headers-5.8.0-55-generic'
  CC [M]  /var/lib/dkms/rtl8821CU/5.4.1/build/core/rtw_cmd.o
In file included from /var/lib/dkms/rtl8821CU/5.4.1/build/include/drv_types.h:30,
                 from /var/lib/dkms/rtl8821CU/5.4.1/build/core/rtw_cmd.c:17:
/var/lib/dkms/rtl8821CU/5.4.1/build/include/wifi.h:1032: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1032 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl8821CU/5.4.1/build/include/osdep_service_linux.h:83,
                 from /var/lib/dkms/rtl8821CU/5.4.1/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821CU/5.4.1/build/core/rtw_cmd.c:17:
./include/linux/ieee80211.h:1600: note: this is the location of the previous definition
 1600 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
In file included from /var/lib/dkms/rtl8821CU/5.4.1/build/include/drv_types.h:78,
                 from /var/lib/dkms/rtl8821CU/5.4.1/build/core/rtw_cmd.c:17:
/var/lib/dkms/rtl8821CU/5.4.1/build/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1/build/include/osdep_service_linux.h:48,
                 from /var/lib/dkms/rtl8821CU/5.4.1/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821CU/5.4.1/build/core/rtw_cmd.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:286: /var/lib/dkms/rtl8821CU/5.4.1/build/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1785: /var/lib/dkms/rtl8821CU/5.4.1/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-55-generic'
make: *** [Makefile:2213: modules] Error 2
